import type { Metadata } from "next";
import { Toaster } from "sonner";
import { AuthGuard } from "@/lib/auth/auth-guard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthGuard>
      <Toaster />
      {children}
    </AuthGuard>
  );
}
